### ISSUE TITLE
[RFC]Change ES5 to ES6

### ISSUE THREAD

**Issue by movie42** [bit101/CodingMath#10]
# Introduction

Hello, my name is Hyunsu Ko. I am working as a front-end developer in South Korea. I wanted to delve into computer graphics and, in my search, found CodingMath to be particularly impressive.

JavaScript has undergone significant changes compared to nine years ago. Notably, the introduction of ES6, the enhancement of type safety with TypeScript, and the advent of build tools like Vite have made the development of JavaScript applications more convenient than ever.

I would like to propose updating the project to use modern JavaScript syntax.

# Proposal

1. Update the repository's code to modern JavaScript syntax.

- Use Vite for the project.
   - Since script injection is handled through Vite, there is no need to use window.onload.
   - The project can be modified to operate as if it's a single application.
- Convert constructors to classes.
- Switch variable declarations from var to const and let.
- Modularize each file using import and export statements.

2. Renewal of the YouTube Course

- If the code is updated, it may be necessary to also renew the course. It would be great if those contributing could also help renew episodes.

# Conclusion

This task will require a significant amount of time and effort. However, I am confident that updating the project to modern JavaScript syntax will greatly aid in understanding how mathematics can be utilized in programming through CodingMath.

I hope there will be much discussion regarding this proposal. Thank you for reading, and I wish you a happy day of development.

**Comment by bit101** [comment]
This is not a JavaScript focused channel. The language, framework, build system, etc. is not the important part of this material. I just went with the bare minimum functionality that everyone would have access to, to show off the mathematical and programming principles. I expect people to to use the ideas in all kinds of languages and platforms. That said, I don't plan to invest any time in upgrading JavaScript or adding other tools.

**Comment by movie42** [comment]
I hadn't thought about that part. Anyway, I'm learning a lot thanks to CodingMath. Thank you!
